apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-data-dashboard-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-data-dashboard
  template:
    metadata:
      labels:
        app: solar-data-dashboard
    spec:
      containers:
      - name: solar-data-dashboard
        image: ghcr.io/yannisyoussef/solar_data_dashboard/solar-data-dashboard:latest
