apiVersion: v1
kind: Service
metadata:
  name: solar-data-dashboard-service
spec:
  selector:
    app: solar-data-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
